name: SpecFlow Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        
    - name: Restore NuGet packages
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --configuration Debug
      
    - name: Get current date and time
      run: echo "::set-output name=datetime::$(Get-Date -Format 'yyyy.MM.dd.HH.mm.ss')"
      shell: powershell
      id: versionWithDateTime
    
    - name: Increment version
      shell: powershell
      id: version
      run: |
        $VERSION = Get-Content -Path Nextzen.Enterprise.BDD\Version.txt
        $VERSION_PARTS = $VERSION.Split(".")
        $MAJOR = $VERSION_PARTS[0]
        $MINOR = $VERSION_PARTS[1]
        $PATCH = $VERSION_PARTS[2]
        # Increment the minor version for a minor change
        $MINOR++
        $NEW_VERSION = "$MAJOR.$MINOR.$PATCH"
        (Get-Content -Path Nextzen.Enterprise.BDD\Version.txt -Raw) -replace $VERSION,$NEW_VERSION | Set-Content -Path Nextzen.Enterprise.BDD\Version.txt
        echo "::set-output name=VER::$NEW_VERSION"
    
    
    - name: Pack
      run: |
        set "PACKAGE_VERSION=%PACKAGE_VERSION%"
        dotnet pack Nextzen.Enterprise.BDD/Nextzen.Enterprise.BDD.csproj --configuration Release --include-symbols --include-source --output ./nupkg /p:PackageVersion=${{ steps.version.outputs.VER }}

    - name: Push generated package to GitHub registry
      run: dotnet nuget push "nupkg/Nextzen.Enterprise.BDD.${{ steps.version.outputs.VER }}.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/saiamarnadh/index.json" --skip-duplicate --no-symbols

